//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace cicapi.Mobile {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CRMIntegration_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/CRMIntegration")]
    public partial class CRMIntegration : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FnMemberStatementStreamOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnIntermediaryrStatementOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CRMIntegration() {
            this.Url = global::cicapi.Properties.Settings.Default.cicapi_Mobile_Mobile;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        public CRMIntegration(string url)
        {
            Url = url;
        }

        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FnMemberStatementStreamCompletedEventHandler FnMemberStatementStreamCompleted;
        
        /// <remarks/>
        public event FnIntermediaryrStatementCompletedEventHandler FnIntermediaryrStatementCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/CRMIntegration:FnMemberStatementStream", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/CRMIntegration", ResponseElementName="FnMemberStatementStream_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/CRMIntegration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void FnMemberStatementStream(string memberNo, ref string bigText, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime from, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime toDate) {
            object[] results = this.Invoke("FnMemberStatementStream", new object[] {
                        memberNo,
                        bigText,
                        from,
                        toDate});
            bigText = ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FnMemberStatementStreamAsync(string memberNo, string bigText, System.DateTime from, System.DateTime toDate) {
            this.FnMemberStatementStreamAsync(memberNo, bigText, from, toDate, null);
        }
        
        /// <remarks/>
        public void FnMemberStatementStreamAsync(string memberNo, string bigText, System.DateTime from, System.DateTime toDate, object userState) {
            if ((this.FnMemberStatementStreamOperationCompleted == null)) {
                this.FnMemberStatementStreamOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnMemberStatementStreamOperationCompleted);
            }
            this.InvokeAsync("FnMemberStatementStream", new object[] {
                        memberNo,
                        bigText,
                        from,
                        toDate}, this.FnMemberStatementStreamOperationCompleted, userState);
        }
        
        private void OnFnMemberStatementStreamOperationCompleted(object arg) {
            if ((this.FnMemberStatementStreamCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnMemberStatementStreamCompleted(this, new FnMemberStatementStreamCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/CRMIntegration:FnIntermediaryrStatement", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/CRMIntegration", ResponseElementName="FnIntermediaryrStatement_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/CRMIntegration", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void FnIntermediaryrStatement(string intermediaryCode, ref string bigText) {
            object[] results = this.Invoke("FnIntermediaryrStatement", new object[] {
                        intermediaryCode,
                        bigText});
            bigText = ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FnIntermediaryrStatementAsync(string intermediaryCode, string bigText) {
            this.FnIntermediaryrStatementAsync(intermediaryCode, bigText, null);
        }
        
        /// <remarks/>
        public void FnIntermediaryrStatementAsync(string intermediaryCode, string bigText, object userState) {
            if ((this.FnIntermediaryrStatementOperationCompleted == null)) {
                this.FnIntermediaryrStatementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnIntermediaryrStatementOperationCompleted);
            }
            this.InvokeAsync("FnIntermediaryrStatement", new object[] {
                        intermediaryCode,
                        bigText}, this.FnIntermediaryrStatementOperationCompleted, userState);
        }
        
        private void OnFnIntermediaryrStatementOperationCompleted(object arg) {
            if ((this.FnIntermediaryrStatementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnIntermediaryrStatementCompleted(this, new FnIntermediaryrStatementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void FnMemberStatementStreamCompletedEventHandler(object sender, FnMemberStatementStreamCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnMemberStatementStreamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnMemberStatementStreamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string bigText {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void FnIntermediaryrStatementCompletedEventHandler(object sender, FnIntermediaryrStatementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnIntermediaryrStatementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnIntermediaryrStatementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string bigText {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591